---
- name: Adiciona usuário openstack no Rabbitmq
  rabbitmq_user:
    user: openstack
    password: RABBIT_PASS
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  tags: rabbitmq
