---
- name: Define configuracao do servidor MySQL
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MySQL
  tags: banco
