---
- name: Define instalacao do servidor MySQL
  import_tasks: install.yml

- name: Define configuracao do servidor MySQL
  import_tasks: configure.yml
 
 - name: Define a segurança do servidor MySQL
  import_tasks: mysql_secure_installation.yml
